config/routes.rb
require 'sidekiq/web'
Rails.application.routes.draw do
  devise_for :users, only: :omniauth_callbacks, controllers: 
  {omniauth_callbacks: 'omniauth_callbacks'}

  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
  
  resources :items
  resources :items_imports
  mount Sidekiq::Web => '/sidekiq'
  get 'items/new'
  get 'items/create'
  get 'items_imports/new'
  get 'items_imports/create'
  get 'pages/home'
  devise_for :users, skip: :omniauth_callbacks
  root to: "students#index"
  get '/search' => 'search#search_student'
  get '/search1' => 'search#search_book'
  resources :students
  get 'download_sample_excel' => 'items_imports#download_sample_excel'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  end
end

app/views/layouts/_footer.html.erb
<!--<div class="container footer_hr">
</div>-->

app/views/layouts/_header.html.erb
<div class="container">
  
  <div class="header_container">
    <% if current_user %>
      <%= link_to t("header.home"), root_path, class: "btn btn-default" %>
      <%= link_to t('header.new_student'), new_student_path, class: "btn btn-default" %>
      <%= link_to t("header.students_list"), root_path, class: "btn btn-default" %>
      <%= link_to t("header.books_list"), items_path, class: "btn btn-default" %>

      <%= link_to t('header.russian'), root_path(locale: :ru), class: "btn btn-default" %>
      <%= link_to t('header.french'), root_path(locale: :fr), class: "btn btn-default" %>
      <%= link_to t('header.english'), root_path(locale: :en), class: "btn btn-default" %>
      <%= link_to t('header.japanese'), root_path(locale: :ja), class: "btn btn-default" %>
      <%= link_to t("header.sign_out"), destroy_user_session_path, method: :delete, class: "btn btn-primary btn-lg float-right" %>
      
    <% else %>
      <%= link_to t("header.sign_in"), new_user_session_path, class: "btn btn-primary" %>
      <%= link_to t("header.sign_up"), new_user_registration_path, class: "btn btn-primary" %>
      <%= link_to t('header.russian'), root_path(locale: :ru), class: "btn btn-primary" %>
      <%= link_to t('header.french'), root_path(locale: :fr), class: "btn btn-primary" %>
      <%= link_to t('header.english'), root_path(locale: :en), class: "btn btn-primary" %>
      <%= link_to t('header.japanese'), root_path(locale: :ja), class: "btn btn-primary" %>
    <% end %>
    
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= t("header.project_1") %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body class="container">
    <%= render "layouts/header" %>
    <hr>
    <%= yield %>
    <%= render "layouts/footer" %>
  </body>
</html>